//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string Name_book { get; set; }
        public int Category_id { get; set; }
        public int Writer_id { get; set; }
        public int For_age { get; set; }
        public string Kind { get; set; }
        public string Symbol_shelf { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date_bringing { get; set; }
        public int Location { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Writer Writer { get; set; }
    }
}
